In [1]:
import re
string = 'bat, lat, mat, bet, let, met, bit, lit, mit, bot, lot, mot'
result = re.findall('b[ao]t', string)
print(result)

['bat', 'bot']


In [11]:
import numpy as np
import math

In [12]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [13]:

l2_dist(20, 20)

AttributeError: 'int' object has no attribute 'sum'

In [15]:
l2_dist(np.reshape(20, (20 * 20)), np.reshape(20, (20 * 20)))

ValueError: cannot reshape array of size 1 into shape (400,)

In [46]:
a1 = np.random.rand(4)
a2 = np.random.rand(4)
a3 = np.array([[1, 2, 3, 4]])
a4 = np.arange(1, 4, 1)
a5 = np.linspace(1 ,4, 4)

In [26]:
a1


array([0.4329658 , 0.42627044, 0.78731653, 0.51901451])

In [27]:
a2

array([0.98082565, 0.48711766, 0.24896184, 0.78518346])

In [40]:
a3

array([[1, 2, 3, 4]])

In [37]:
a4

array([1, 2, 3])

In [34]:
a5

array([1., 2., 3., 4.])

In [42]:
a4.ndim() == 1

TypeError: 'int' object is not callable

In [43]:
a3.shape == a4.shape

False

In [47]:
a1.shape == a2.shape

True

In [48]:
a5.shape == a1.shape

True

In [49]:
a1.shape

(4,)

In [50]:
a2.shape

(4,)

In [51]:
a5.shape

(4,)

In [52]:
import numpy as np

old = np.array([[1, 1, 1], [1, 1, 1]])
new = old
new[0, :2] = 0

print(old)

[[0 0 1]
 [1 1 1]]


In [53]:
import re 
s = 'ACBCAC'

In [56]:
re.findall('^AC',s)

['AC']

In [57]:
re.findall('[^A]C', s)

['BC']

In [58]:

re.findall('^[AC]', s)

['A']

In [59]:
import re
s = 'ACAABAACAAAB'
result = re.findall('A{1,2}', s)
L = len(result)

In [60]:
print(L)

5


In [61]:
import re

In [71]:
text = 'I refer to https://www.baidu.comand I never refer http://www.google.com if I have to search anything'

In [81]:
re.findall("(?<=[https]:\/\/)([A-Za-z0-9.]*)",text)

['www.baidu.comand', 'www.google.com']

In [88]:
text=r'''Everyone has the following fundamental freedoms:
    (a) freedom of conscience and religion;
    (b) freedom of thought, belief, opinion and expression, including freedom of the press and other media of communication;
    (c) freedom of peaceful assembly; and
    (d) freedom of association.'''

import re
pattern = '\(.\)'
print(len(re.findall(pattern,text)))

4


In [94]:
a = np.random.rand(20)

In [96]:
b = np.random.rand(20)

In [97]:
def l2_dist(a, b):
    result = ((a - b) * (a - b)).sum()
    result = result ** 0.5
    return result 

In [98]:
l2_dist(a,b)

1.9873456793439845

In [100]:
l2_dist(np.reshape(np.random.rand(20), (20 * 20)), np.reshape(np.random.rand(20), (20 * 20)))

ValueError: cannot reshape array of size 20 into shape (400,)