In [1]:
import numpy as np
import math

# Array Creation

In [25]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [26]:
print(a.ndim)

1


In [33]:
b = np.array([[1.0,2,3],[4,5,6]])
b

array([[1., 2., 3.],
       [4., 5., 6.]])

In [34]:

print(b.ndim)

2


In [35]:
b.shape

(2, 3)

In [36]:
b.dtype

dtype('float64')

In [38]:
c = np.array([2.2,5,1.1])

In [39]:
c.dtype.name

'float64'

In [40]:
c

array([2.2, 5. , 1.1])

In [41]:
d = np.zeros((2,3))
print(d)
e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [56]:
a = np.array(([1,3],[3,4],[5,7]))


In [44]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
np.array([a[0,0],a[1,1],a[2,1]])

array([1, 4, 6])

In [61]:
print(a[[0,1,2],[0,1]])

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [ ]:
a = np.array([[]])